//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusStop
    {
        public BusStop()
        {
            this.BusStopUpdateList = new HashSet<BusStopUpdateList>();
            this.ElectricityBill = new HashSet<ElectricityBill>();
        }
    
        public int BSID { get; set; }
        public string Name { get; set; }
        public int BSCID { get; set; }
        public string Address { get; set; }
        public string Direction { get; set; }
        public string District { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
    
        public virtual BusStopClass BusStopClass { get; set; }
        public virtual ICollection<BusStopUpdateList> BusStopUpdateList { get; set; }
        public virtual ICollection<ElectricityBill> ElectricityBill { get; set; }
    }
}
