//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricityBill
    {
        public ElectricityBill()
        {
            this.ElectricityBillUpdateList = new HashSet<ElectricityBillUpdateList>();
        }
    
        public string EBID { get; set; }
        public short EBYear { get; set; }
        public short EBMonth { get; set; }
        public string PayType { get; set; }
        public string Address { get; set; }
        public int KWh { get; set; }
        public int TotalCost { get; set; }
        public int ProcessNumber { get; set; }
        public int TID { get; set; }
        public int BSID { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual ICollection<ElectricityBillUpdateList> ElectricityBillUpdateList { get; set; }
        public virtual BusStop BusStop { get; set; }
    }
}
