//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModel
    {
        public TaskModel()
        {
            this.Task = new HashSet<Task>();
            this.TaskModelDetail = new HashSet<TaskModelDetail>();
        }
    
        public int TMID { get; set; }
        public int TCID { get; set; }
        public Nullable<short> StepCount { get; set; }
    
        public virtual ICollection<Task> Task { get; set; }
        public virtual TaskClass TaskClass { get; set; }
        public virtual ICollection<TaskModelDetail> TaskModelDetail { get; set; }
    }
}
